Update deathMessages.json
Bobthe28th/CaptureTheFart pull request #69
Opened 2022-02-02 03:01 UTC by Tman2143

death mesaged

2022-02-02 03:16 UTC, Bobthe28th requested changes
You used "fucking" in like half the messages

2022-02-02 03:16 UTC, Bobthe28th commented on src/me/bobthe28th/capturethefart/ctf/deathMessages.json
> +    "wizardZap": ["$1 got zapped by $2","$1 got electrocuted to fucking death by $2","$1 got absolutally smited to death by $2"],
```suggestion
    "wizardZap": ["$1 got zapped by $2","$1 got electrocuted to fucking death by $2","$1 got absolutely smited to death by $2"],

```

2022-02-02 03:16 UTC, Bobthe28th commented on src/me/bobthe28th/capturethefart/ctf/deathMessages.json
> +    "wizardZap": ["$1 got zapped by $2","$1 got electrocuted to fucking death by $2","$1 got absolutally smited to death by $2"],
```suggestion
    "wizardZap": ["$1 got zapped by $2","$1 got electrocuted to fucking death by $2","$1 got absolutally smote to death by $2"],

```

2022-02-02 03:16 UTC, Bobthe28th commented on src/me/bobthe28th/capturethefart/ctf/deathMessages.json
> +    "builderAxe": ["$1 got hella hella 90s built on them by $2","$1 lost the build battle to $2","$1 could not escape maze built by $2"],
```suggestion
    "builderAxe": ["$1 got hella 90s built on them by $2","$1 lost the build battle to $2","$1 could not escape maze built by $2"],

```

2022-02-02 17:04 UTC, Bobthe28th commented on src/me/bobthe28th/capturethefart/ctf/deathMessages.json
> +    "wizardZap": ["$1 got zapped by $2","$1 got electrocuted to fucking death by $2","$1 got absolutally smited to death by $2"],
Just spell 4head

2022-02-02 17:05 UTC, Bobthe28th commented on src/me/bobthe28th/capturethefart/ctf/deathMessages.json
> +    "builderAxe": ["$1 got hella hella 90s built on them by $2","$1 lost the build battle to $2","$1 could not escape maze built by $2"],
Prob when you fixed order of $1 and $1 you made extra hella?

2022-02-02 17:08 UTC, Bobthe28th commented
Also there is wizardZap (left click) and wizardLightning (right click) idk if that will change the death messages but yea

2022-02-02 17:29 UTC, Bobthe28th commented
Also this is #69, nice

2022-02-02 19:50 UTC, Tman2143 commented
> You used "fucking" in like half the messages

yea that's like half the fun

2022-02-04 02:09 UTC, Bobthe28th commented
can you look at the changes I requested?

2022-02-04 05:37 UTC, Bobthe28th commented on src/me/bobthe28th/capturethefart/ctf/deathMessages.json
> +    "wizardZap": ["$1 got zapped by $2","$1 got electrocuted to fucking death by $2","$1 got absolutally smited to death by $2"],
Ill resolve

2022-02-04 05:38 UTC, Bobthe28th approved these changes
Zamn!

2022-02-04 05:40 UTC, Bobthe28th commented
> Also there is wizardZap (left click) and wizardLightning (right click) idk if that will change the death messages but yea

also this

2022-02-04 05:46 UTC, merged